baseURL = "https://brugui.dev/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Alejandro Brugarolas · Brugui"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Alejandro Brugarolas"
  email = "alejandro.brugarolas@gmail.com"
  description = "Software Engineer"
  bio = "Full Stack Developer.  \nFlutter Advocate"
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "Nothing to see here..."
  
  [params.contact]
    github = "https://github.com/Brugui7"
    instagram = "https://instagram.com/imbrugui"
    linkedin = "https://www.linkedin.com/in/alejandro-brugarolas/"
